---
title: "Assignment 1"
output: html_notebook
---

This assignment will practice your ability to set up an R project, download and extract data into an R data set and apply useful operations to the data set.  

The project will use a github repository and a kaggle data set.  You must create your analysis in an R notebook.

1. Create a github repository called Kiva.  It will hold analyis for *Data Science for Good: Kiva Crowdfunding* 
Make sure you initialize a README.

2. On your computer, clone this repository into your *Documents* directory. Add a data subfolder.

3. Download the Kaggle dataset for *Data Science for Good: Kiva Crowdfunding* to your computer, put the zip files in the
data sub directory.  Unzip them and them delete the zip versions.

4. Apply different data methods to the *loans* dataset.  
    1. Count the unique ID by sector.  
    2. Create side by side box plot for five interesting levels of sector and funding amount.
    3. Create a new field called *gender* with only the three values *male* and *female* or NA.
    4. Create a scatter plot overlay of funding amount by loan amount for the two levels of *gender*
    5. create a data set with *ID*, *gender* and *Tag*, but have a separate record for each listed tag.
    6. Count and sort to show the top five tags for males vs. females.
    
5. Extra credit.  Learn something interesting about the data set and publish your kernel in Kaggle and present it to the class.
     
  
